# Generated by Django 2.1.5 on 2019-01-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Detail',
        ),
    ]
