# Generated by Django 2.1.5 on 2019-01-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students_app', '0002_auto_20190127_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('fathers_name', models.CharField(max_length=256)),
                ('address', models.TextField(max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('passing_year', models.DurationField()),
                ('roll_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic')),
            ],
        ),
    ]
