# Generated by Django 2.1.5 on 2019-01-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_students_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students_Details',
            new_name='Student',
        ),
    ]
